framework:
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/config/validator/"

when@test:
    framework:
        validation:
            not_compromised_password: false
