version: '3'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8088:80"

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html:cached

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  redis:
    image: redis

volumes:
  db-data: