FROM php:8.2-fpm

RUN apt-get update && apt-get install -y libpq-dev libicu-dev \
    && docker-php-ext-install pdo pgsql pdo_pgsql \
    && pecl install xdebug  \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-enable intl \
    && pecl install redis \
    && docker-php-ext-enable redis;

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
